### ISSUE TITLE
lightweight

### ISSUE THREAD

**Issue by sh1man999** [kwon-evan/LPRNet#1]
how did you get such a lightweight file lprnet_kor.pt

**Comment by kwon-evan** [comment]
I just rewrote the model into pytorch-lightning, trained it, and got the results.
I don't know the details, but I'm guessing the model was designed to lightweight.

**Comment by sh1man999** [comment]
Why is the output ckpt and not pt and the file weighs almost a gigabyte

**Comment by kwon-evan** [comment]
Simply rename the file from .ckpt to .pt.
I'm not sure about the size of the trained model, mine was 16 bits.
