### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by CODINGHYE** [kwon-evan/LPRNet#11]
Hi @kwon-evan !!
Could you share me what dataset did you use for training?
I found the commit that you post about dataset and searched through Korea public data portal, but I couldn't find it.
Or do you mean the dataset posted on AI hub site?

**Comment by kwon-evan** [comment]
Hi @CODINGHYE,

Yes, I used a dataset from the AI hub.
I used [this one](https://www.aihub.or.kr/aihubdata/data/view.do?currMenu=115&topMenu=100&dataSetSn=172), and I think [this one](https://www.aihub.or.kr/aihubdata/data/view.do?currMenu=115&topMenu=100&aihubDataSe=data&dataSetSn=71573) will work too.
I think any license plate images would probably work well.

**Comment by CODINGHYE** [comment]
Thanks for your reply!! It was very helpful!!
