### ISSUE TITLE
Square license plate

### ISSUE THREAD

**Issue by sh1man999** [kwon-evan/LPRNet#2]
I want to recognize rectangular numbers and square numbers, what settings need to be set in the configuration.

![image](https://github.com/kwon-evan/LPRNet/assets/20192431/27d991d0-c183-430d-bd26-db7c5697d562)
![image](https://github.com/kwon-evan/LPRNet/assets/20192431/0a80e656-445a-4d8b-8627-34e75dbf45e9)

**Comment by kwon-evan** [comment]
you are using alphabet and numbers. i think you can use [idn-config.yaml](https://github.com/kwon-evan/LPRNet/blob/master/config/idn_config.yaml).
1. prepare train, valid, test datasets. format as follow:
```
train/
 ├ AB2394.jpg
 ├ EZ555I.jpg
 ├ AA0000BB-0.jpg
  ...
```
2. change config path in [train.py](https://github.com/kwon-evan/LPRNet/blob/785ccf0d591b2b4fdb2c6f35d67a974a2b7245ad/train.py#L17)
3. image size will be automatically resized and padded

**Comment by sh1man999** [comment]
what size should I specify in the configuration? 100x100 ?

**Comment by kwon-evan** [comment]
It should only be able to take rectangular shapes as input, I haven't tried sizes other than (100, 50). It probably won't work, or it will be inaccurate.
