### ISSUE TITLE
Trained model accuracy

### ISSUE THREAD

**Issue by cannguyen275** [kwon-evan/LPRNet#3]
Hello,
Might you share accuracy of your trained model: weights/lprnet_kor.pt
Thanks!

**Comment by kwon-evan** [comment]
![lprnet-result](https://github.com/kwon-evan/LPRNet/assets/87924725/94bc6bf4-765d-4c9b-a0d6-47dbcfbc14c4)
This is train log in my experiment. about 90% in validation.
and the data is korean license plate dataset given by korea public data portal.

**Comment by cannguyen275** [comment]
Thanks @kwon-evan, just trained a new model based on your code base.
I've faced some issues with NaN CTC and low accuracy. By adding some improvements, I finally achieve ~93%.
Let me create some PR for this.

**Comment by kwon-evan** [comment]
Glad to hear that! I've been looking for ways to improve accuracy too, feel free to PR me anytime.
